### ISSUE TITLE
`sendEvent` could fail and cause `unhandledrejection`, which is unexpected for webpack dev overlay

### ISSUE THREAD

**Issue by JounQin** [Barbapapazes/plausible-tracker#11]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@barbapapazes/plausible-tracker@0.5.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@barbapapazes/plausible-tracker/dist/index.mjs b/node_modules/@barbapapazes/plausible-tracker/dist/index.mjs
index a682ac4..1910b54 100644
--- a/node_modules/@barbapapazes/plausible-tracker/dist/index.mjs
+++ b/node_modules/@barbapapazes/plausible-tracker/dist/index.mjs
@@ -30,7 +30,7 @@ function sendEvent(apiHost, payload, callback) {
     body: JSON.stringify(payload)
   }).then(() => {
     callback?.();
-  });
+  }).catch(() => {});
 }
 
 function createPayload(eventName, plausibleOptions, data, options) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by JounQin** [comment]
The request could fail on a lot of cases, such as incorrect configuration, client blocking, network error, etc.

**Comment by Barbapapazes** [comment]
Hey, thank you for your feedback! 🙌

I will update the tracker!
