### ISSUE TITLE
`enabled: false` does not work as expected

### ISSUE THREAD

**Issue by JounQin** [Barbapapazes/plausible-tracker#12]
`enabled` option is not used at all in the source codes.

**Comment by Barbapapazes** [comment]
Ah, this is annoying. I'll take a look

**Comment by Barbapapazes** [comment]
Do you have a use case with this option? I think it's an artifact during the forking and it could be removed.

**Comment by Barbapapazes** [comment]
I finally decided to allow Plausible to be disabled with an early return in the `trackEvent` function.
