### ISSUE TITLE
`logIgnored` option sets the opposite behavior

### ISSUE THREAD

**Issue by obulat** [Barbapapazes/plausible-tracker#15]
## Description

When a host is ignored, and `logIgnoredEvents` is set to `true`, the events are not logged in the console.
```
ignoredHostnames: ["localhost"],
logIgnoredEvents: false,
```

It seems that the code here is reversing the behavior: it logs is `logIgnoredEvents` is set to `false`, and does not log when `logIgnoredEvents` is set to `true`.

https://github.com/Barbapapazes/plausible-tracker/blob/4dde4fa4b70c16fdf4df98825e5fd32f6b659d16/src/plausible.ts#L51

**Comment by Barbapapazes** [comment]
Hey 👋,

Thanks for reporting this! I will have a look at the PR.
