### ISSUE TITLE
Consider replacing `blackListedDomains` with `ignoredDomains`

### ISSUE THREAD

**Issue by johannschopplich** [Barbapapazes/plausible-tracker#7]
I'm reaching out to discuss the use of the term `blackListedDomains` within the codebase. Given the evolving understanding and sensitivity towards language in technology, I propose we update this terminology to `deniedDomains` or `disallowedDomains` or `ignoredDomains`.

I'd like to suggest updating the term `blackListedDomains` to `ignoredDomains` in your codebase. This change aligns with industry trends towards more inclusive language, as seen with companies like GitHub, Apple, and Linux Foundation moving away from terms like ["blacklist" and "whitelist"](https://en.wikipedia.org/wiki/Blacklist_(computing)#Controversy_over_use_of_the_term).

Adopting `ignoredDomains` promotes inclusivity and avoids potential racial connotations associated with "blacklist." Making this shift not only reflects a commitment to respectful and welcoming language but also keeps us in step with broader tech community standards.

I believe this is a meaningful yet simple update. What do you think? 🙂

**Comment by johannschopplich** [comment]
Also, shouldn't the wording be `host` instead of `domain`? 🤔

**Comment by Barbapapazes** [comment]
Hey,

did not saw this! (because it's a fork, github does not enable notification by default) but that's a very good idea!
